name: Deploy Hugo Site

on:
  push:
    branches:
      - testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: Setup Hugo
    #   uses: peaceiris/actions-hugo@v2
    #   with:
    #     hugo-version: 'latest'
    #     extended: true

    # - name: Build Hugo Site
    #   run: hugo --source ./website

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: ${{ secrets.DOCS_USER }}
        key: ${{ secrets.DOCS_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.DOCS_USER }}/trueblocks-key/website
          echo pwd `pwd`
          git pull origin testing
          npm run build
          chown -R ${{ secrets.DOCS_USER }}:trueblocks public
          find public -exec grep -His everything {} ';'
          cp -pR public/* /var/www/trueblocks-key/html/
